### ISSUE TITLE
FHIR valuesets not accessible

### ISSUE THREAD

**Issue by kaboyles** [IHTSDO/snowstorm#213] opened 2021-01-21 11:58 UTC
Hello, 

Our customer is unable to access the FHIR valuesets in our test snowstorm server.

Several calls to the API's, regardless of method answers:

  {
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Failed to call access method: java.lang.NullPointerException"
    }
  ]
}

It works in our production and qa environments.

Any hints? 

Thanks,
Kim

**Comment by pgwilliams** [comment] 2021-01-21 13:06
Hi Kim   When you try try the call they're making yourself, do you see the same thing?   What shows up in the logs?   We've made a lot of updates to the FHIR API in the last week or so, could you also confirm what version you're running?  Thanks!

**Comment by pgwilliams** [comment] 2021-01-21 13:13
But in any event, if anyone is seeing a NullPointerException then that's a fault with our code.  We should be detecting whatever the problem is and replying with some informative error about the cause.

**Comment by Tannjorn** [comment] 2021-01-21 13:46
I have some more info that might help, while we are waiting for our supplier to get the logs.

We have three "identical" servers with slightly different content. But there is one major difference at the time of update, the server which is now sending a NullPointerException had a few ValueSets in place. There others had none.

**Comment by kaboyles** [comment] 2021-01-21 14:50
Snowstorm version 5.0.6 for all three servers.

**Comment by pgwilliams** [comment] 2021-01-21 15:32
Great.  If you can get me the call that is being made, that would help also.  Thanks!

**Comment by Tannjorn** [comment] 2021-01-21 18:58
Yes, all servers are 5.0.6. Would you think a patch/upgrade could help? Is there a newer version available?

Anyway. You can use this https://test.terminologi.ehelse.no/fhir/ValueSet in a browser. I have used the same in Postman, test.terminologi.ehelse.no/fhir as the baseUrl and ValueSet as the only additional function. I have also tried with further queries like trying to expand a specific set, but the error remains the same.

Our two other base URLs are terminologi.ehelse.no and qa.terminologi.ehelse.no.

Trying to use the functions CodeSystem or Translate works fine on all servers.

**Comment by pgwilliams** [comment] 2021-01-22 10:47
Oh you're seeing the error even on the basic type url for all ValueSets?   Yes there is a newer version available (6.0.0 available on Master to build but not yet published as a Jar), but we didn't change anything in the rendering of ValueSets so I wouldn't expect it to fix the issue.    I think the code must be expecting one or more fields to be populated in your VS and they haven't been.  This explains when you only see it in your test server.  So if you can get me that Exception stack trace from the logs then I can tell you which field it is and you can re-create that ValueSet to fix the problem.    I will also fix the code to do something more helpful in this situation!

**Comment by Zawaken** [comment] 2021-01-22 11:09
Here's the exception stack we see in the logs.
Let me know if you need any more info.

```2021-01-22 11:47:17.827 ERROR 9586 --- [http-nio-8080-exec-10] c.u.f.r.s.i.ExceptionHandlingInterceptor : Failure during REST processing

ca.uhn.fhir.rest.server.exceptions.InternalErrorException: Failed to call access method: java.lang.NullPointerException
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:244)
        at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:256)
        at ca.uhn.fhir.rest.server.method.SearchMethodBinding.invokeServer(SearchMethodBinding.java:49)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.doInvokeServer(BaseResourceReturningMethodBinding.java:247)
        at ca.uhn.fhir.rest.server.method.BaseResourceReturningMethodBinding.invokeServer(BaseResourceReturningMethodBinding.java:384)
        at ca.uhn.fhir.rest.server.RestfulServer.handleRequest(RestfulServer.java:1002)
        at ca.uhn.fhir.rest.server.RestfulServer.doGet(RestfulServer.java:336)
        at ca.uhn.fhir.rest.server.RestfulServer.service(RestfulServer.java:1695)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at io.kaicode.rest.util.branchpathrewrite.BranchPathUriRewriteFilter.doFilter(BranchPathUriRewriteFilter.java:50)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.snomed.snowstorm.rest.security.RequestHeaderAuthenticationDecoratorWithRequiredRole.doFilterInternal(RequestHeaderAuthenticationDecoratorWithRequiredRole.java:43)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ca.uhn.fhir.rest.server.method.BaseMethodBinding.invokeServerMethod(BaseMethodBinding.java:239)
        ... 79 common frames omitted
Caused by: java.lang.NullPointerException: null
        at org.snomed.snowstorm.fhir.domain.ValueSetWrapper.getValueSet(ValueSetWrapper.java:50)
        at org.snomed.snowstorm.fhir.services.FHIRValueSetProvider.lambda$findValuesets$0(FHIRValueSetProvider.java:157)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:901)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.snomed.snowstorm.fhir.services.FHIRValueSetProvider.findValuesets(FHIRValueSetProvider.java:159)
        ... 84 common frames omitted```

**Comment by pgwilliams** [comment] 2021-01-22 11:37
Sweet,  thank you so much for that log  I see the problem.  I'll see how quickly I can get a fix into the build.

FYI @kaicode

**Comment by pgwilliams** [comment] 2021-01-22 14:24
Would you be able to try installing this release and let me know how it goes please?  https://github.com/IHTSDO/snowstorm/releases/tag/5.1.1

We're also publishing 6.0.1 in the next week or so.   That build will not include this fix so you'll want to skip that one and we'll see about a 6.0.2 at some point that will include this particular fix.

**Comment by kaboyles** [comment] 2021-01-25 12:17
Patch seems to be working at initial glance/internally.  Thanks!!  Tannjorn can update more on what the customer is seeing.

**Comment by Tannjorn** [comment] 2021-02-02 17:14
Closing this, as further testing confirms that all is now good.

**Comment by Tannjorn** [comment] 2021-02-02 17:15
This issue can now be closed, as further testing has confirmed that all is good.

**Comment by pgwilliams** [comment] 2021-02-03 09:00
Thanks for confirming @kaboyles & @Tannjorn !

**Closed by pgwilliams** 2021-02-03 09:00 UTC
Labels: bug, fixed-in-dev
