### ISSUE TITLE
ECL relationship group 0 mapping

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#22] opened 2019-01-08 20:30 UTC
Compared results from snowstorm 2.1.0, 2.0.0 as well as current sct-snapshot-rest-api and OntoServer and there are some differences. See: https://confluence.ihtsdotools.org/display/SLPG/ECL+and+grouped+attributes?focusedCommentId=78938364#comment-78938364

Copied from above (but formatting seems to have been lost):

1. << 71388002 | atgard | : {  363703001 | har avsikt | = << 129428001 | preventiv avsikt |  }
2. << 71388002 | atgard | : 363703001 | har avsikt | = << 129428001 | preventiv avsikt | 

implementation | SNOMED CT release | Query 1 | Query 2
-- | -- | -- | --
sct-snapshot-rest-api, commit 3ce4ab6 | The one I had on my hard drive, likely International 2018-01-31 | 91 | 91
snowstorm, v 2.1.0 | SE edition 2018-11-30 | 9 | 523
OntoServer through Shrimp UI, buildid ddd5953f1d34f52fb9f5d79a5d910e5d2f4bfaf4487755d3f8f6a5c7ea12a81c | International 2018-01-31 | 347 | 347
snowstorm through browser, v 2.0.0 (https://browser.ihtsdotools.org/ecl/) | International 2018-07-31 | 7 | 347

Expected to have the same results from the two queries.

**Comment by rorydavidson** [comment] 2019-01-09 07:52
To add some more info here, Snow Owl v5 produces the same results as snowstorm v2.0.0 for both queries on the 2018-07-31 release.

**Comment by kaicode** [comment] 2019-01-09 09:15
Hi @danka74, 
I've responded on Confluence but will dual post here.

> If the SLPG group agrees that any attribute which is grouped in the MRCM Attribute Domain reference set should be treated as grouped for ECL query purposes I would be happy to change the Snowstorm implementation.

Cheers.

**Comment by kaicode** [comment] 2019-02-14 14:06
This is a confirmed bug because the ECL specification was not correctly interpreted. It should be fixed. The July 2019 release of the International Edition of SNOMED CT will introduce explicit grouping of all attributes which are marked as grouped in the MRCM so this problem will resolve itself, but it would be nice to have correct ECL evaluation against existing SNOMED releases.

**Comment by kaicode** [comment] 2019-11-08 11:49
This has resolved itself in the July 2019 International release and any extension which uses it because self grouped attributes which were in group 0 are now explicitly self grouped using a non zero group number.

**Closed by kaicode** 2019-11-08 11:49 UTC
Labels: bug
