### ISSUE TITLE
How could i delete a branch/code system? 

### ISSUE THREAD

**Issue by liquid36** [IHTSDO/snowstorm#98] opened 2020-01-23 12:45 UTC
Hi!
I want to know if it is posible to delete a code system or a branch from Snowstorm? 

Thanks!

**Comment by kaicode** [comment] 2020-01-23 13:20
Hi there,

It's not currently possible in the latest release of Snowstorm but there is a new branch delete admin function in the git develop branch. You are right that being able to delete a code system would be helpful too! I'll add that in the next couple of weeks. 

In the meantime you can always delete the code system document from the Elasticsearch index if you need a workaround.

Cheers, Kai

**Comment by kaicode** [comment] 2020-01-23 13:35
SNOMED International Internal Jira ticket MAINT-1164

**Comment by kaicode** [comment] 2020-01-23 14:21
I've pushed a delete codesystem API endpoint to the develop branch.

**Comment by kaicode** [comment] 2020-01-23 14:23
The travis build is failing because the build log is too long. This is caused by some new Elasticsearch warnings since I switched the version that the unit tests are using. Should be fixed at some point.

**Comment by liquid36** [comment] 2020-01-23 14:24
Okey! Thanks

**Comment by kaicode** [comment] 2020-02-13 15:52
This is fixed in [Release 4.7.1](https://github.com/IHTSDO/snowstorm/releases).

There is a new API endpoint:
`DELETE /codesystems/{shortName}`
This function deletes the code system and its versions but it does not delete the branches or the content.

If you also need to delete the branch and the content this endpoint has also been added:
`DELETE /admin/{branch}/actions/hard-delete`
Hard delete a branch including its content and history.

Cheers

**Closed by kaicode** 2020-02-13 15:52 UTC
Labels: enhancement
