### ISSUE TITLE
MRCM Range search - wrong language

### ISSUE THREAD

**Issue by liquid36** [IHTSDO/snowstorm#589] opened 2024-04-25 11:50 UTC
Hi! me again...
I trying the MRCM endpoints. When i want to search for attributes values in Spanish, Snowstorm insist to search in English. Example: 

```
curl -X 'GET' \
  'http://localhost:8080/mrcm/MAIN%2FSNOMEDCT-ES%2FSNOMEDCT-AR/attribute-values/263502005?contentType=NEW_PRECOORDINATED&termPrefix=crónico' \
  -H 'accept: application/json' \
  -H 'Accept-Language: es'
```

But if i change _crónico_ by _chronic_, i get values.

Searching for query logs in Elasticsearch, i found that Snowstorm is setting the languageCode to **en**:

```
{
    "from": 0,
    "size": 10000,
    "query": {
        "bool": {
            "must": [
                ... BRANCH CRITERIA 
                {
                    "terms": {
                        "languageCode": [
                            "en"
                        ],
                        "boost": 1.0
                    }
                },
                {
                    "term": {
                        "active": {
                            "value": true
                        }
                    }
                }
            ],
            "filter": [
                {
                    "bool": {
                        "must": [
                            {
                                "bool": {
                                    "should": [
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        },
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        },
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        },
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        },
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        },
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        },
                                        {
                                            "bool": {
                                                "filter": [
                                                    {
                                                        "query_string": {
                                                            "query": "chronic*",
                                                            "fields": [
                                                                "termFolded^1.0"
                                                            ],
                                                            "default_operator": "and",
                                                            "boost": 2.0
                                                        }
                                                    }
                                                ],
                                                "boost": 1.0
                                            }
                                        }
                                    ],
                                    "boost": 1.0
                                }
                            }
                        ],
                        "boost": 1.0
                    }
                }
            ],
            "boost": 1.0
        }
    },
    "version": true,
    "_source": {
        "includes": [
            "descriptionId",
            "conceptId"
        ],
        "excludes": []
    },
    "sort": [
        {
            "termLen": {
                "order": "asc",
                "mode": "min"
            }
        },
        {
            "_score": {
                "order": "asc"
            }
        }
    ]
}
```
It appears that the **Accept-Language header** is only utilized for the response, rather than the query.

**Comment by kaicode** [comment] 2024-04-25 13:09
@liquid36 I was able to reproduce this problem. Yes it looks like Snowstorm currently limits the MRCM attribute search stage to English terms. I've created a code fix for this on branch `mrcm-language-fix`. Would you able to build and test this?

**Comment by liquid36** [comment] 2024-04-25 13:25
Could you provide me instruction about how to build it? I'm not an expert on maven. 
A Dockerfile would be great.

**Comment by liquid36** [comment] 2024-04-25 14:25
It's working as i expected! Thanks very much. You could release the fix.

**Comment by kaicode** [comment] 2024-04-25 15:06
Great! Thanks for testing. I will raise a ticket for the technical team to merge this in.

**Comment by kaicode** [comment] 2024-04-25 15:11
Raised internal ticket INFRA-12853

**Comment by liquid36** [comment] 2024-06-27 14:04
Was this fix included in the last release?

**Comment by kaicode** [comment] 2024-06-27 15:01
This fix did not make it into the last release. It's still in the develop branch at the moment.

**Closed** 2024-08-30 09:51 UTC
Labels: bug

**Comment by kaicode** [comment] 2024-08-30 10:15
The fix for this issue is included in release 10.4.2.
