### ISSUE TITLE
Using Elastic Search 8.2.3

### ISSUE THREAD

**Issue by johnsonf79** [IHTSDO/snowstorm#421] opened 2022-06-27 10:06 UTC
Encountering error while running snowstorm-7.1.2.jar to snowstorm-7.8.0.jar using elastic search 8.2.3 but doesnt work

for e.g. java -Xms2g -Xmx4g -jar snowstorm-7.8.0.jar --snowstorm.rest-api.readonly=true

2022-06-27 12:42:12.177  WARN 7584 --- [           main] o.s.data.convert.CustomConversions       : Registering converter from interface java.util.Map to class org.springframework.data.elasticsearch.core.geo.GeoPoint as reading converter although it doesn't convert from a store-supported type! You might want to check your annotation setup at the converter implementation.
2022-06-27 12:42:12.317  INFO 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Spring Data Elasticsearch: 4.0.4
2022-06-27 12:42:12.317  INFO 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client in build: 7.6.2
2022-06-27 12:42:12.317  INFO 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client used: 7.7.0
2022-06-27 12:42:12.317  WARN 7584 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version mismatch in between Elasticsearch Clients build/use: 7.6.2 - 7.7.0
2022-06-27 12:42:12.518  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.599  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.661  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.724  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.755  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.786  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:12.880  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:13.564  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:13.564  INFO 7584 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Identifier cache manager polling commencing with 10 second period.
2022-06-27 12:42:13.626  INFO 7584 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 02) by 4000
2022-06-27 12:42:13.736  WARN 7584 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection is closed; nested exception is java.lang.RuntimeException: Connection is closed
2022-06-27 12:42:13.876 ERROR 7584 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Failed to top-up IdCache(0 - 02) with 4000 identifiers

**Comment by kaicode** [comment] 2022-06-27 10:08
This seems to be a duplicate of #420. Please see the response on that ticket. Many thanks.

**Closed by kaicode** 2022-06-27 10:08 UTC

**Comment by robert-khuh** [comment] 2022-06-29 07:32
2022-06-29 10:28:48.966  INFO 6156 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Spring Data Elasticsearch: 4.0.4
2022-06-29 10:28:48.982  INFO 6156 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client in build: 7.6.2
2022-06-29 10:28:48.982  INFO 6156 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version Elasticsearch Client used: 7.7.0
2022-06-29 10:28:48.982  WARN 6156 --- [           main] o.s.d.elasticsearch.support.VersionInfo  : Version mismatch in between Elasticsearch Clients build/use: 7.6.2 - 7.7.0

Hello kaicode,

above is expected problem if I use snowstorm-7.8.0, even tried with snowstorm-7.0.X
??

So is it strictly for es vs 7.6.2 only?

**Comment by robert-khuh** [comment] 2022-06-29 07:43
> 2022-06-29 10:28:48.966 INFO 6156 --- [ main] o.s.d.elasticsearch.support.VersionInfo : Version Spring Data Elasticsearch: 4.0.4 2022-06-29 10:28:48.982 INFO 6156 --- [ main] o.s.d.elasticsearch.support.VersionInfo : Version Elasticsearch Client in build: 7.6.2 2022-06-29 10:28:48.982 INFO 6156 --- [ main] o.s.d.elasticsearch.support.VersionInfo : Version Elasticsearch Client used: 7.7.0 2022-06-29 10:28:48.982 WARN 6156 --- [ main] o.s.d.elasticsearch.support.VersionInfo : Version mismatch in between Elasticsearch Clients build/use: 7.6.2 - 7.7.0
> 
> Hello kaicode,
> 
> above is expected problem if I use snowstorm-7.8.0, even tried with snowstorm-7.0.X ??
> 
> So is it strictly for es vs 7.6.2 only?

I found the issue? if ssl is enabled for elastic search, data loading / starting snowstorm will not work.... just tried disabling ssl and it started

**Comment by robert-khuh** [comment] 2022-06-29 08:24
How can i pass username and password while loading snomed - to elastic search when https enabled with security pack=true

**Comment by kaicode** [comment] 2022-06-29 08:42
I have found that it's safe to ignore the warning message about "Version mismatch in between Elasticsearch Clients build". As long as the server version is the same or greater than the client version and they are the same major version.

SNOMED International always keeps Elasticsearch behind a firewall, never accessible on the public internet. We keep the security pack disabled. 

Although Elastic.co promote the security features and there have been recent news items related to Elasticsearch security, my understanding is that this is only because some Elasticsearch instances have been left completely open to the public internet!

A username and password can be provided using the `elasticsearch.username` and `elasticsearch.password` configuration settings. These should work with SSL. When Elasticsearch is accessed over HTTPS it will probably not work with port 9200, I would recommend using the standard SSL port instead.

I hope that helps.
