### ISSUE TITLE
Elasticsearch exception when searching for concepts

### ISSUE THREAD

**Issue by Eneuman** [IHTSDO/snowstorm#359] opened 2022-01-02 23:18 UTC
Hi

I have a list of concept ids that I want to check if they are children to a specific concept.
I'm trying to use "GET /{branch}/concepts" to do this.

I am setting the branch to "MAIN/SNOMEDCT-SE", ecl to "< 404684003 | kliniskt fynd |" and conceptids to "161891005".
The rest of the values have there default values.
When running this query, elastic search craches with the following error:

{
  "error": "INTERNAL_SERVER_ERROR",
  "message": "Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]; nested exception is ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [65000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Result window is too large, from + size must be less than or equal to: [10000] but was [65000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.]];"
}

Request URL: `http://localhost:8080/MAIN%2FSNOMEDCT-SE/concepts?ecl=%3C%20404684003%20%7C%20kliniskt%20fynd%20%7C&conceptIds=161891005&offset=0&limit=50`

The strange thing is that it works if I search against MAIN, but not against another branch.

Is this a bug?
Is there a better way to do this query?

**Comment by kaicode** [comment] 2022-01-04 10:59
Hi @Eneuman, happy new year.

Thank you for reporting this. I assume you are using the latest Snowstorm release. There is a confirmed bug related to the new ECL cache. You can disable the cache as a workaround until this is fixed. Please see #358 for further details.

I will close this ticket because it's the same issue as #358 but thanks again for raising it!
Kind regards.

**Closed by kaicode** 2022-01-04 10:59 UTC

**Comment by Eneuman** [comment] 2022-01-04 11:18
Thanks for the info :)

Quick question: 
What would be fastest, a query with concept ids and a ecl or a query where you have combined the concept ids with the ecl like "< 1654263 AND (753264 OR 8522654 OR 32685437)"

Regards
Per

**Comment by kaicode** [comment] 2022-01-04 11:50
Once the cache is working I think using the `ecl` and `conceptIds` parameters would be fastest. Without the cache there doesn't seem to be any difference. Using `&returnIdOnly=true` helps.
