### ISSUE TITLE
Repeated warnings: number of terms exceeded allowed maximum

### ISSUE THREAD

**Issue by nhnicwaller** [IHTSDO/snowstorm#12] opened 2018-11-08 23:59 UTC
I noticed a large number of WARN events (repeated 98 times) being written to the Elasticsearch log while I had an import in progress.

> [2018-11-08T23:38:06,216][WARN ][o.e.d.i.q.TermsQueryBuilder] Deprecated: the number of terms [342029] used in the Terms Query request has exceeded the allowed maximum of [65536]. This maximum can be set by changing the [index.max_terms_count] index level setting.

The same warning was returned back to the Elasticsearch RestClient and logged by snowstorm (12 times).

> 2018-11-08 23:40:57.115  WARN 155 --- [/O dispatcher 1] org.elasticsearch.client.RestClient      : request [GET http://localhost:9200/es-query/query-concept/_search?typed_keys=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&scroll=60000ms&search_type=query_then_fetch&batched_reduce_size=512] returned 1 warnings: [299 Elasticsearch-6.4.2-04711c2 "Deprecated: the number of terms [384272] used in the Terms Query request has exceeded the allowed maximum of [65536]. This maximum can be set by changing the [index.max_terms_count] index level setting." "Thu, 08 Nov 2018 23:40:53 GMT"]

What is the status of this warning?

- Is this an unexpected warning?
- Or is it expected, but not a concern?
- Or is it expected, and I should adjust my settings in order to avoid printing the warning?

It looks like this warning [will become a hard error in 7.0](https://github.com/elastic/elasticsearch/pull/27968#issuecomment-356897363).

### Additional Details

- Elasticsearch 6.4.2
- Snowstorm 2.1.0

**Comment by kaicode** [comment] 2018-11-09 10:01
@nhnicwaller Thank you for being thorough and providing valuable feedback.

This is an expected warning and it's caused by the process which builds the semantic indexes based on the imported relationship changes.

At the moment this one is expected but not a concern. I aim to refactor the code to remove this issue before upgrading to Elasticsearch 7.0 (whenever that becomes available).

Let's leave this issue open to track that.

**Comment by kaicode** [comment] 2020-07-10 14:57
We are now working on the Elasticsearch 7 upgrade but it is likely we will recommend the workaround suggested in https://github.com/IHTSDO/snowstorm/issues/51#issuecomment-628899049 to resolve this.

**Comment by rorydavidson** [comment] 2020-10-28 13:38
Closing as, since v5, Snowstorm has been upgraded to work with Elasticsearch 7.

**Closed by rorydavidson** 2020-10-28 13:38 UTC
Labels: bug, warning
