### ISSUE TITLE
Why can't I upload any version of Loinc

### ISSUE THREAD

**Issue by edwardlo12** [IHTSDO/snowstorm#642] opened 2024-11-26 02:44 UTC
I have tried Loinc 2.71, 2.72, 2.76-2.78  
But all i get is the following error:
```json
{
  "resourceType": "OperationOutcome",
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-1141: Unknown file: hapi-fhir-cli18413190268715013472.zip"
  } ]
}
```
Here's the software virsion I used:
hapi-fhir-cli: 7.6.0
snowstrom: 10.5.1

**Comment by kaicode** [comment] 2024-11-26 10:00
This is a bug caused by misalignment of the Jena library. We will work on a fix for this.

**Comment by edwardlo12** [comment] 2024-11-28 09:10
Thanks🙏🏻

**Closed** 2024-11-28 09:10 UTC
Labels: bug
